export class OrderStatusConstants {

  static INPROGRESS = 'INPROGRESS';
  static INPROGRESSALL = 'INPROGRESSALL';
  static COMPLETED = 'COMPLETED';
  static DROPPED = 'DROPPED';
  static DROP_WHOLE_ORDER = 'DROP_WHOLE_ORDER';
}

export class OrderItemStatusConstants {
  static REVERTFROMCANCEL = 'REVERTFROMCANCEL';
  static ORDER_CANCEL_FOR_ITEM = 'ORDER_CANCEL_FOR_ITEM';
  static ORDER_PLACED_FOR_ITEM = 'ORDER_PLACED_FOR_ITEM';
  static ORDER_INPROGRESS_FOR_ITEM = 'ORDER_INPROGRESS_FOR_ITEM';
  static ORDER_COMPLETED_FOR_ITEM = 'ORDER_COMPLETED_FOR_ITEM';


}

