export class OrderConstantComponent {


  static ORDERED_PLACED = 'ORDERED_PLACED';
  static IN_PROGRESS = 'INPROGRESS';
  static COMPLETED = 'COMPLETED';
  static DROP_WHOLE_ORDER = 'ABSOLUTE';


  static ORDER_PLACED_FOR_ITEM = 'ORDER_PLACED_FOR_ITEM';
  static ORDER_INPROGRESS_FOR_ITEM = 'ORDER_INPROGRESS_FOR_ITEM';
  static ORDER_COMPLETED_FOR_ITEM = 'ORDER_COMPLETED_FOR_ITEM';
  static ORDER_CANCEL_FOR_ITEM = 'ORDER_CANCEL_FOR_ITEM';


}
